version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - GOOGLE_CLOUD_KEYFILE=./gcp-key.json
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - trusttech_network
    volumes:
      - ./gcp-key.json:/app/gcp-key.json:ro

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=trusttech
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trusttech_network

networks:
  trusttech_network:
    driver: bridge

volumes:
  postgres_data:
