version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLOUD_KEYFILE=/app/gcp-key.json
      - NODE_ENV=production
    volumes:
      - ./gcp-key.json:/app/gcp-key.json:ro
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
    networks:
      - trusttech_network

networks:
  trusttech_network:
    driver: bridge
